#server:
#  port: 8082
#
#spring:
#  application:
#    name: ticket-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ticket_service
#    username: postgres
#    password: Welcome@1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  jackson:
#    mapper:
#      accept-case-insensitive-enums: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: user-service
#    instance-id: ${spring.application.name}:${server.port}
#
#file:
#  upload-dir: ./uploads
#  max-size: 50MB
#  allowed-types: "*"
#  public-url-prefix: /api/v1/files
#
#camel:
#  springboot:
#    name: ticketService-camel
#debug: false


server:
  port: 8082

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ticket_service
    username: postgres
    password: Welcome@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: user-service
    instance-id: ${spring.application.name}:${server.port}

file:
  upload-dir: ./uploads
  max-size: 50MB
  allowed-types: "*"
  public-url-prefix: /api/v1/files